package experience

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func GenerateGo(ir SemanticIR, outputPath string) error {
	if ir.Schema != IRScheme || len(ir.Nodes) != 12 || ir.SourceDigest == "" || ir.ContractDigest == "" {
		return errors.New("semantic IR is not generation-ready")
	}
	if !filepath.IsAbs(outputPath) {
		return errors.New("generated output must be an absolute caller-owned path")
	}
	var b strings.Builder
	b.WriteString("// Code generated by gooo-experience-memory; DO NOT EDIT.\n")
	b.WriteString("package generated\n\n")
	fmt.Fprintf(&b, "const SourceDigest = %q\n", ir.SourceDigest)
	fmt.Fprintf(&b, "const ContractDigest = %q\n", ir.ContractDigest)
	irDigest := DigestIR(ir)
	fmt.Fprintf(&b, "const IRDigest = %q\n\n", irDigest)
	b.WriteString("type ActivityBinding struct {\n\tOrdinal int\n\tID string\n\tActivity string\n\tIRNode string\n\tMetricID string\n\tEvaluator string\n}\n\n")
	b.WriteString("var Activities = []ActivityBinding{\n")
	for _, node := range ir.Nodes {
		fmt.Fprintf(&b, "\t{Ordinal: %d, ID: %q, Activity: %q, IRNode: %q, MetricID: %q, Evaluator: %q},\n", node.Ordinal, node.ID, node.Activity, node.ID, node.MetricID, node.Evaluator)
	}
	b.WriteString("}\n")
	b.WriteString("\n// gooo.generated.binding.count=12\n")
	for _, node := range ir.Nodes {
		fmt.Fprintf(&b, "// gooo.generated.cell=%02d id=%s activity=%s evaluator=%s\n", node.Ordinal, node.ID, node.Activity, node.Evaluator)
	}
	data := []byte(b.String())
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, data, 0o644)
}

func ValidateGenerated(path string, ir SemanticIR) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	text := string(data)
	for _, marker := range []string{"package generated", "SourceDigest = \"" + ir.SourceDigest + "\"", "ContractDigest = \"" + ir.ContractDigest + "\"", "IRDigest = \"" + DigestIR(ir) + "\"", "gooo.generated.binding.count=12"} {
		if !strings.Contains(text, marker) {
			return "", fmt.Errorf("generated Go is missing binding marker %q", marker)
		}
	}
	for _, node := range ir.Nodes {
		marker := "gooo.generated.cell=" + twoDigits(node.Ordinal) + " id=" + node.ID + " activity=" + node.Activity + " evaluator=" + node.Evaluator
		if strings.Count(text, marker) != 1 {
			return "", fmt.Errorf("generated Go binding is not one-to-one for %s", node.Activity)
		}
	}
	return DigestBytes(data), nil
}

func twoDigits(value int) string {
	if value < 10 {
		return "0" + strconv.Itoa(value)
	}
	return strconv.Itoa(value)
}
